from typing import Protocol

from cog.core.item import Item


class StateCache(Protocol):
    def is_processed(self, item: Item) -> bool: ...
    def mark_processed(self, item: Item, outcome: str) -> None: ...
    def is_deferred(self, item: Item) -> bool: ...
    def mark_deferred(self, item: Item, reason: str, blockers: list[str]) -> None: ...
    def clear_deferral(self, item: Item) -> None: ...
    def save(self) -> None: ...
